CREATE DATABASE RoyalGamesDB

USE RoyalGamesDB
GO

CREATE TABLE Usuario
(
UsuarioId INT IDENTITY PRIMARY KEY,
Nome NVARCHAR(60) NOT NULL,
Email VARCHAR(70) NOT NULL,
Senha VARBINARY(32) NOT NULL,
StatusUsuario BIT NOT NULL
);
GO

CREATE TABLE Plataforma
(
PlataformaId INT IDENTITY PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
Genero NVARCHAR(20) NOT NULL
);

GO

CREATE TABLE Promocao
(
	PromocaoId INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	DataExpiração DATETIME NOT NULL,
	StatusPromocao BIT NOT NULL
);

GO

CREATE TABLE Genero
(
GeneroId INT IDENTITY PRIMARY KEY,
Nome VARCHAR(50) NOT NULL
);

GO

CREATE TABLE ClassificacaoIndicativa
(
ClassificacaoIndicativaId INT IDENTITY PRIMARY KEY,
Classificacao VARCHAR(50) NOT NULL
);

GO

CREATE TABLE Jogo
(
JogoId INT IDENTITY PRIMARY KEY,
Nome VARCHAR(150),
Descrição NVARCHAR(255),
Preço DECIMAL(10,2),
--PlataformaIdFK INT NOT NULL,
--PromocaoIdFK INT NOT NULL,
--ClassificacaoIdFK INT NOT NULL,

--CONSTRAINT FK_Jogo_Classificacao FOREIGN KEY(ClassificacaoIdFK) REFERENCES ClassificacaoIndicativa(ClassificacaoIndicativaId) ON DELETE CASCADE,
--CONSTRAINT FK_Jogo_Plataforma FOREIGN KEY (PlataformaIdFK) REFERENCES Plataforma(PlataformaId) ON DELETE CASCADE,
--CONSTRAINT FK_Jogo_Promocao FOREIGN KEY (PromocaoIdFK) REFERENCES Promocao(PromocaoId) ON DELETE CASCADE

);

GO

CREATE TABLE Log_Alteracao_Jogo
(
	Log_Alteracao_Jogo_Id INT IDENTITY PRIMARY KEY,
	DataAlteracao DATETIME NOT NULL,
	NomeAnterior VARCHAR(100) NOT NULL,
	PrecoAnterior DECIMAL(10,2) NOT NULL,
	JogoIdFK INT NOT NULL

	CONSTRAINT FK_LogAlteracao_Jogo FOREIGN KEY (JogoIdFK) REFERENCES Jogo(JogoId)
	ON DELETE CASCADE
);

GO

CREATE TABLE JogoPlataforma 
(
--JogoPlataforma INT IDENTITY PRIMARY KEY,
PlataformaIdFK INT NOT NULL,
JogoIdFK INT NOT NULL,
CONSTRAINT Jogo_Plataforma_Id_FK PRIMARY KEY(PlataformaIdFK, JogoIdFK),



CONSTRAINT FK_JogoPlataforma_Plataforma FOREIGN KEY (PlataformaIdFK) REFERENCES Plataforma(PlataformaId) ON DELETE CASCADE,
CONSTRAINT FK_JogoPlataforma_Jogo FOREIGN KEY (JogoIdFK) REFERENCES Jogo(JogoId) ON DELETE CASCADE
);

GO


CREATE TABLE JogoGenero
(
JogoIdFK INT NOT NULL,
GeneroIdFK INT NOT NULL,

CONSTRAINT Jogo_Genero_Id_FK PRIMARY KEY(JogoIdFK, GeneroIdFK),

CONSTRAINT FK_JogoGenero_Jogo FOREIGN KEY(JogoIdFK) REFERENCES Jogo(JogoId) ON DELETE CASCADE,
CONSTRAINT FK_JogoGenero_Genero FOREIGN KEY (GeneroIdFK) REFERENCES Genero(GeneroId) ON DELETE CASCADE
);


GO


CREATE TABLE JogoPromocao
(
	JogoIdFK INT NOT NULL,
	PromocaoIdFK INT NOT NULL,
	CONSTRAINT Jogo_Promocao_Id_FK PRIMARY KEY(JogoIdFK, PromocaoIdFK),

	CONSTRAINT FK_JogoPromocao_Jogo FOREIGN KEY(JogoIdFK) REFERENCES Jogo(JogoId) ON DELETE CASCADE,
	CONSTRAINT FK_JogoPromocao_Promocao FOREIGN KEY(PromocaoIdFK) REFERENCES Promocao(PromocaoId) ON DELETE CASCADE
);





